import type { VsLibraryManifest } from '../types.js';

export const VS_LIBRARY: VsLibraryManifest = {
    version: '0.0.2',
    extensions: [
        'aaron-bond.better-comments',
        'anthropic.claude-code',
        'anysphere.remote-ssh',
        'bierner.markdown-mermaid',
        'bierner.markdown-preview-github-styles',
        'bradlc.vscode-tailwindcss',
        'christian-kohler.npm-intellisense',
        'christian-kohler.path-intellisense',
        'dbaeumer.vscode-eslint',
        'donjayamanne.githistory',
        'dracula-theme.theme-dracula',
        'dsznajder.es7-react-js-snippets',
        'eamodio.gitlens',
        'ecmel.vscode-html-css',
        'esbenp.prettier-vscode',
        'firsttris.vscode-jest-runner',
        'formulahendry.auto-rename-tag',
        'meta.pyrefly',
        'mikestead.dotenv',
        'ms-python.debugpy',
        'ms-python.python',
        'ms-python.vscode-python-envs',
        'ms-vscode.live-server',
        'naumovs.color-highlight',
        'orta.vscode-jest',
        'pflannery.vscode-versionlens',
        'pkief.material-icon-theme',
        'sibiraj-s.vscode-scss-formatter',
        'steoates.autoimport',
        'streetsidesoftware.code-spell-checker',
        'streetsidesoftware.code-spell-checker-vietnamese',
        'usernamehw.errorlens',
        'vscode-icons-team.vscode-icons',
        'wix.vscode-import-cost',
        'xabikos.javascriptsnippets',
    ],
    settings: {
        'workbench.iconTheme': 'material-icon-theme',
        'editor.fontFamily': "'Fira Code'",
        'editor.fontLigatures': true,
        'editor.fontSize': 14,
        '[typescript]': {
            'editor.defaultFormatter': 'esbenp.prettier-vscode',
        },
        '[typescriptreact]': {
            'editor.defaultFormatter': 'esbenp.prettier-vscode',
        },
        '[scss]': {
            'editor.defaultFormatter': 'esbenp.prettier-vscode',
        },
        '[json]': {
            'editor.defaultFormatter': 'esbenp.prettier-vscode',
        },
        'javascript.updateImportsOnFileMove.enabled': 'always',
        'typescript.updateImportsOnFileMove.enabled': 'always',
        'editor.codeActionsOnSave': {
            'source.fixAll.eslint': 'explicit',
            'source.fixAll': 'explicit',
        },
        'typescript.preferences.importModuleSpecifier': 'relative',
        'javascript.preferences.importModuleSpecifier': 'relative',
        'workbench.colorTheme': 'Dracula Theme',
        'explorer.compactFolders': false,
        'gitlens.views.scm.grouped.views': {
            commits: true,
            branches: true,
            remotes: true,
            stashes: false,
            tags: true,
            worktrees: true,
            contributors: true,
            repositories: false,
            searchAndCompare: false,
            launchpad: false,
        },
        'extensions.ignoreRecommendations': true,
        'diffEditor.ignoreTrimWhitespace': true,
        'workbench.settings.applyToAllProfiles': [],
        'workbench.activityBar.iconClickBehavior': 'toggle',
        'terminal.integrated.defaultProfile.windows': 'PowerShell',
        'jest.enable': false,
        'cSpell.userWords': ['automapper', 'dtos', 'ILIKE', 'Redlock', 'refinedev', 'Serper'],
        'editor.unicodeHighlight.ambiguousCharacters': false,
        'terminal.integrated.defaultProfile.osx': 'zsh',
        'git.confirmSync': false,
        'cSpell.enabled': true,
        'cSpell.language': 'en,vi',
        'terminal.integrated.profiles.osx': {
            bash: {
                path: 'bash',
                args: ['-l'],
                icon: 'terminal-bash',
            },
            zsh: {
                path: 'zsh',
                args: ['-l'],
            },
            fish: {
                path: 'fish',
                args: ['-l'],
            },
            tmux: {
                path: 'tmux',
                icon: 'terminal-tmux',
            },
            pwsh: {
                path: 'pwsh',
                icon: 'terminal-powershell',
            },
            csh: {
                path: '/bin/csh',
            },
        },
        'editor.formatOnSave': true,
        'workbench.editor.showTabs': 'multiple',
        'workbench.editor.tabSizing': 'shrink',
        'window.autoDetectColorScheme': false,
        'workbench.editorAssociations': {
            '*.md': 'vscode.markdown.preview.editor',
        },
        'python.languageServer': 'None',
        'git.autofetch': true,
        'explorer.confirmDelete': false,
        'workbench.sideBar.location': 'right',
        'markdown-preview-github-styles.colorTheme': 'light',
        'markdown-preview-github-styles.darkTheme': 'dark_dimmed',
        'markdown-preview-github-styles.lightTheme': 'light',
    },
};
