import { formatCursorCommandFile } from '@/core/command-generation/adapters/cursor.js';
import { STRUCTURALS_DIR } from '@/core/structure/paths.js';

export const STRUCTURE_APPLY_SKILL_NAME = 'only-one-structure-apply';
export const STRUCTURE_APPLY_SKILL_DIR = STRUCTURE_APPLY_SKILL_NAME;
export const STRUCTURE_APPLY_COMMAND_ID = STRUCTURE_APPLY_SKILL_NAME;
export const STRUCTURE_APPLY_SLASH = '/only-one-structure-apply';

export const STRUCTURE_APPLY_BLUEPRINT_NAMING_HINT = `{organization}-{project}-structural.md under .only-one/${STRUCTURALS_DIR}/`;

export const STRUCTURE_APPLY_SKILL_DESCRIPTION =
    'Initialize a new source code layout and structure from a structural blueprint markdown file. Requires a blueprint file generated by structure-generate.';

export const buildStructureApplySkillBody =
    (): string => `Initialize a new source code repository structure/layout using the structural blueprint markdown file.

**Source blueprint path:** \`.only-one/${STRUCTURALS_DIR}/{organization}-{project}-structural.md\` (or custom path).

---

**Role**: You are an Expert Software Engineer and Project Scaffolder.

**Task**: Read the structural blueprint markdown file, analyze its Tech Stack, Directory Skeleton, and Coding Conventions, and scaffold/initialize the physical directory structure, config files, and core file skeletons of the project.

**CRITICAL RULE**: Do NOT write any business/domain logic. Scaffold folders, standard configuration files (like package.json, tsconfig.json, eslint, prettier config), barrel files (index.ts), and empty structural skeletons as defined in the blueprint.

Structure sections of the blueprint to process:
1. Tech Stack & Core Tooling -> Create package/configuration files (package.json, config, etc.) and lockfiles if applicable.
2. Structural Skeleton -> Recreate directory structure and add empty structural placeholder files.
3. Architectural Paradigms -> Create architectural directories and boundaries.
4. Structural Coding Conventions -> Ensure new files follow the specified naming and structure.

---

**Steps**

1. **Confirm the blueprint path** via CLI:
   \`\`\`bash
   only-one-cli structure-apply [path] --json
   \`\`\`
   Parse \`projectDir\`, \`outputPath\`, \`relativeBlueprintPath\`, \`blueprintFile\`.

2. **Read the structural blueprint file** at the resolved \`outputPath\`.

3. **Track with TodoWrite** — read blueprint → scaffold folder tree → generate core configs → create structural skeleton files → verify build.

4. **Scaffold the codebase** — create directory directories and file skeletons.

5. **Verify** that code builds and print confirmation.

**Guardrails**
- Do NOT run \`openspec\` CLI or create \`openspec/changes/\`
- Do NOT include domain entities, user stories, or feature names
- Do NOT paste raw source code
- Ask before overwrite unless the user requested regeneration
`;

export const buildStructureApplySkillMarkdown = (cliVersion: string): string => `---
name: ${STRUCTURE_APPLY_SKILL_NAME}
description: ${STRUCTURE_APPLY_SKILL_DESCRIPTION}
license: MIT
compatibility: Requires only-one-cli CLI.
metadata:
  author: only-one-cli
  version: "1.0"
  generatedBy: "${cliVersion}"
---

${buildStructureApplySkillBody()}
`;

export const buildStructureApplyCommandContent = (): import('../command-generation/types.js').CommandContent => ({
    body: buildStructureApplySkillBody(),
    category: 'Workflow',
    description: STRUCTURE_APPLY_SKILL_DESCRIPTION,
    id: STRUCTURE_APPLY_COMMAND_ID,
    name: STRUCTURE_APPLY_SKILL_NAME,
    tags: ['only-one-cli', 'structure-apply'],
});

export const buildStructureApplyCommandFile = (): string =>
    formatCursorCommandFile({
        body: buildStructureApplySkillBody(),
        category: 'Workflow',
        description: STRUCTURE_APPLY_SKILL_DESCRIPTION,
        id: STRUCTURE_APPLY_COMMAND_ID,
        slashName: STRUCTURE_APPLY_SLASH,
    });

export type StructureApplyPlaybookStep = {
    id: string;
    summary: string;
};

export const getStructureApplyPlaybookSteps = (): StructureApplyPlaybookStep[] => [
    { id: 'scaffold', summary: `CLI confirms structural blueprint path` },
    { id: 'skills', summary: 'Ensure agent skills are installed (structure-apply will prompt if missing)' },
    { id: 'resolve', summary: 'Run only-one-cli structure-apply [path] --json to confirm outputPath' },
    { id: 'read', summary: 'Read structural blueprint from outputPath' },
    { id: 'scaffold-dirs', summary: 'Re-create directory structure and add base configuration files' },
    { id: 'verify', summary: 'Confirm source skeleton has been initialized successfully' },
];
