import type { ComboManifest } from '../types.js';

export const COMBOS: ComboManifest[] = [
    {
        id: 'frontend-flow',
        name: 'Frontend Flow Setup',
        description: 'Next.js and React frontend development toolkit',
        packages: ['ui-ux-pro-max-cli'],
        skills: [
            'grill-with-docs',
            'grill-me',
            'interview-me',
            'idea-refine',
            'to-tickets',
            'codebase-design',
            'c4-diagrams',
            'gherkin-authoring',
            'only-one-nextjs-development',
            'frontend-ui-engineering',
            'performance-optimization',
            'code-simplification',
            'incremental-implementation',
            'test-driven-development',
            'diagnosing-bugs',
            'doubt-driven-development',
            'source-driven-development',
            'handoff',
            'resolving-merge-conflicts',
        ],
        rules: ['next-architecture-stack', 'context-and-tools'],
        workflows: [
            'only-one-idea',
            'only-one-plan',
            'only-one-apply',
            'only-one-debug',
            'only-one-review',
            'only-one-handoff',
            'only-one-conflict',
            'only-one-archive',
            'only-one-clean',
        ],
    },
    {
        id: 'backend-flow',
        name: 'Backend Flow Setup',
        description: 'NestJS backend development toolkit with architecture design, security audit, and API standards',
        skills: [
            'grill-with-docs',
            'grill-me',
            'interview-me',
            'idea-refine',
            'to-tickets',
            'codebase-design',
            'c4-diagrams',
            'gherkin-authoring',
            'only-one-nestjs-development',
            'api-and-interface-design',
            'security-and-hardening',
            'code-simplification',
            'incremental-implementation',
            'test-driven-development',
            'diagnosing-bugs',
            'doubt-driven-development',
            'source-driven-development',
            'handoff',
            'resolving-merge-conflicts',
        ],
        rules: ['nest-architecture-stack', 'context-and-tools'],
        workflows: [
            'only-one-idea',
            'only-one-plan',
            'only-one-apply',
            'only-one-debug',
            'only-one-review',
            'only-one-handoff',
            'only-one-conflict',
            'only-one-archive',
            'only-one-clean',
        ],
    },
    {
        id: 'full-sdlc-flow',
        name: 'Full SDLC Enterprise Flow Setup',
        description: 'Complete end-to-end SDLC toolkit: Ideation, Dual-layer planning, quality gates, security, webperf, and review',
        skills: [
            'grill-with-docs',
            'grill-me',
            'interview-me',
            'idea-refine',
            'domain-modeling',
            'wait-what',
            'to-tickets',
            'codebase-design',
            'c4-diagrams',
            'gherkin-authoring',
            'only-one-nestjs-development',
            'only-one-nextjs-development',
            'frontend-ui-engineering',
            'api-and-interface-design',
            'security-and-hardening',
            'performance-optimization',
            'code-simplification',
            'incremental-implementation',
            'test-driven-development',
            'context-engineering',
            'prototype',
            'wizard',
            'diagnosing-bugs',
            'doubt-driven-development',
            'source-driven-development',
            'handoff',
            'resolving-merge-conflicts',
            'code-review-and-quality',
            'only-one-clockify-skill',
            'only-one-intranet-skill',
            'only-one-pr-git-skill',
        ],
        rules: ['nest-architecture-stack', 'next-architecture-stack', 'context-and-tools'],
        workflows: [
            'only-one-idea',
            'only-one-plan',
            'only-one-apply',
            'only-one-debug',
            'only-one-review',
            'only-one-handoff',
            'only-one-conflict',
            'only-one-archive',
            'only-one-clean',
            'only-one-clockify',
            'only-one-intranet',
            'only-one-pr-git',
        ],
    },
    {
        id: 'mcp-flow',
        name: 'MCP Flow Setup',
        description: 'Model Context Protocol (MCP) servers toolkit',
        mcps: ['fetch', 'tavily', 'github', 'clockify', 'zodinet-timesheet', 'postgres'],
    },
    {
        id: 'git-timesheet-flow',
        name: 'Git & Timesheet Flow Setup',
        description: 'GitHub PR, Clockify, and Intranet Timesheet logging integration toolkit',
        skills: ['only-one-clockify-skill', 'only-one-intranet-skill', 'only-one-pr-git-skill'],
        workflows: ['only-one-clockify', 'only-one-intranet', 'only-one-pr-git'],
    },
];
