import type { ComboManifest } from '../types.js';

export const COMBOS: ComboManifest[] = [
    {
        id: 'frontend-flow',
        name: 'Frontend Flow Setup',
        description: 'Next.js and React frontend development toolkit',
        packages: [
            '@fission-ai/openspec',
            'ui-ux-pro-max-cli',
            'next-dev-loop',
            'next-cache-components-adoption',
            'next-cache-components-optimizer',
            'next-partial-prefetching-adoption',
        ],
        mcps: ['gitnexus', 'fetch', 'tavily', 'github', 'clockify'],
        plugins: ['superpowers'],
        skills: [
            'c4-diagrams',
            'gherkin-authoring',
            'grill-me',
            'only-one-clockify-skill',
            'only-one-pr-git-skill',
            'only-one-gitnexus-freshness',
            'only-one-openspec-apply-gate',
            'only-one-bounded-discovery',
            'only-one-openspec-phase-planning',
            'only-one-phase-implementation-loop',
            'only-one-canonical-ref-gate',
            'only-one-component-inventory',
            'only-one-ui-design-direction',
        ],
        configs: ['openspec'],
        rules: ['architecture-stack', 'context-and-tools'],
        workflows: [
            'only-one-plan-fe',
            'only-one-implement-fe',
            'only-one-implement-fast',
            'only-one-bug',
            'only-one-clockify',
            'only-one-pr-git',
        ],
    },
    {
        id: 'backend-flow',
        name: 'Backend Flow Setup',
        description: 'NestJS backend development toolkit',
        packages: ['@fission-ai/openspec'],
        mcps: ['gitnexus', 'postgres', 'github', 'clockify'],
        plugins: ['superpowers'],
        skills: [
            'c4-diagrams',
            'gherkin-authoring',
            'grill-me',
            'only-one-clockify-skill',
            'only-one-pr-git-skill',
            'only-one-gitnexus-freshness',
            'only-one-openspec-apply-gate',
            'only-one-bounded-discovery',
            'only-one-openspec-phase-planning',
            'only-one-phase-implementation-loop',
        ],
        configs: ['openspec'],
        rules: ['architecture-stack', 'context-and-tools'],
        workflows: [
            'only-one-plan-be',
            'only-one-implement-be',
            'only-one-implement-fast',
            'only-one-bug',
            'only-one-clockify',
            'only-one-pr-git',
        ],
    },
];
